# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Simple text replacement
  # - trigger: ":espanso"
  #   replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  # URLs
  - trigger: ";mylin"
    replace: "https://www.linkedin.com/in/robcreel/"

  - trigger: ";myport"
    replace: "https://robcreel.github.io/"

  # R snippets
  - trigger: ";rass"
    replace: "-> "
  
  - trigger: ";eopra"
    replace: "identity() ->"

    
  # Dumb job URL domain password manager problem password
  - trigger: ";jobpw"
    replace: "ksjdfhSDKLFJH20583)#*&%Y"

  # DSH Intro
  - trigger: ";dshintro"
    replace: "Hi hi!  I'm Rob, in Chicago.  I'm hunting for a data analytics/engineering role.  I brew coffee, take pictures, and collect ThinkPads.
\nhttps://www.linkedin.com/in/robcreel/"
